DRONE_WIDTH = .75 # if in meters
DIST_TO_GOAL_TOL = .1 # meters
CAM_TIMEOUT = 30 # seconds
PREV_DETECTION = 10 # seconds
NS = "Samwise"
X_BOUND = 8
Y_BOUND = 8
MAX_AXIS_VELOCITY = 0.2 # m/s
DEGREE_TOL = 0.174533 # 10 degrees